# This is the default fetch script. This was generated by wilpac.

echo "- wilpac-main:"; if cd wilpac-main 2>/dev/null; then git pull --progress |& sed 's/^/     /g'; else git clone https://github.com/CrazyWillBear/wilpac-main |& sed 's/^/   /g'; fi